### ISSUE TITLE
forwards are duplicated when ultimate_stats and CSX module running simultaneously

### ISSUE THREAD

**Issue by rivit98** [TheDoctor0/UltimateStats#6]
If CSX is running and ultimate_stats too then forwards (like client_death, bomb_planted) are called twice.

Posible solution:
1. detect if CSX is running and warn user
2. simply set_fail_state + proper information.
3. disable csx automatically (set_module_filter or 'meta unload' command)
4. or maybe something better

Also, if this is replacement for CSX it should also support custom_weapon_* and xmod_* natives or just display information about lack of support.

EDIT:
Oh, I haven't noticed .so module (because I tested it on Windows), my bad.

**Comment by TheDoctor0** [comment]
About CSX, there is ["dummy" version](https://github.com/TheDoctor0/UltimateStats/blob/master/cstrike/addons/amxmodx/modules/csx_amxx_i386.so) of this module is provided with plugin. I didn't specify it in README, but it must be used instead default CSX module and that's why it's also included in every release.
It can be replaced, but firstly UltimateStats need to register csx library.

Proper support for custom_weapon_* / xmod_* natives would require dynamically adding new fields to database tables - which of course can be done, but I don't think that it's really worth it, because those are rarely used in general. 
Despite that, it's a good idea to actually partially implement them to use only with default weapon for compatibility with some plugins (and throw errors in other cases).
